### ISSUE TITLE
application issue when the link is opened

### ISSUE THREAD

**Issue by aryanpatel142006** [Aryanpatel335/Post-Pic-Flask-App#1]
Hi Bro 

There is some application issue when the link is opened.

**Comment by Aryanpatel335** [comment]
Hey,

Thanks for pointing this out. Unfortunately, the link is broken as the app was hosted on Heroku and they no longer have free hosting so the link can no longer work. I will have to make a video demo with the app locally sometime in the future.

:)

**Comment by Aryanpatel335** [comment]
Closing issue
